name: SonarQube Scan

on:
  push:
    branches: [ main ]

jobs:
  sonarQubeScan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java (for scanner)
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=myproject
            -Dsonar.projectName=MyProject
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "http://localhost:9000"
